### ISSUE TITLE
Báo lỗi dịch thuật

### ISSUE THREAD

**Issue by sant1ago-hn** [sant1ago-da-hanoi/oni-mods-descriptions#1]
Mọi góp ý liên quan đến bản dịch của mình, mọi người có thể thảo luận tại đây.

**Comment by dhm1207** [comment]
hi gs, mình report mấy lỗi kỳ cục như này
1. Space biome dịch thành phím cách
2. Lỗi dịch của máy ép bùn
3. "temporal tear closed" với lổ hổng không gian cũng chưa được dịch
![image](https://user-images.githubusercontent.com/90306428/132458457-b9a494ff-dc58-4732-a56c-79f9827bfcfb.png)
![image](https://user-images.githubusercontent.com/90306428/132458482-006f4daf-7999-4430-9b87-ca631c4c8082.png)

**Comment by dhm1207** [comment]
một số mô tả của công trình cũng chưa được dịch
![image](https://user-images.githubusercontent.com/90306428/132459204-d924662e-cfcf-41c4-8474-692ea41fa8b9.png)
![image](https://user-images.githubusercontent.com/90306428/132459214-cf2d3b0e-282b-4d2e-ba77-81b344fe1891.png)
![image](https://user-images.githubusercontent.com/90306428/132459219-4ec797fa-4b97-4c59-a9f8-2188fdc589f6.png)

**Comment by sant1ago-hn** [comment]
> hi gs, mình report mấy lỗi kỳ cục như này
> 
> 1. Space biome dịch thành phím cách
> 2. Lỗi dịch của máy ép bùn
> 3. "temporal tear closed" với lổ hổng không gian cũng chưa được dịch
>    ![image](https://user-images.githubusercontent.com/90306428/132458457-b9a494ff-dc58-4732-a56c-79f9827bfcfb.png)
>    ![image](https://user-images.githubusercontent.com/90306428/132458482-006f4daf-7999-4430-9b87-ca631c4c8082.png)

`DONE`

**Comment by sant1ago-hn** [comment]
> một số mô tả của công trình cũng chưa được dịch
> ![image](https://user-images.githubusercontent.com/90306428/132459204-d924662e-cfcf-41c4-8474-692ea41fa8b9.png)
> ![image](https://user-images.githubusercontent.com/90306428/132459214-cf2d3b0e-282b-4d2e-ba77-81b344fe1891.png)
> ![image](https://user-images.githubusercontent.com/90306428/132459219-4ec797fa-4b97-4c59-a9f8-2188fdc589f6.png)

`DONE`

**Comment by dhm1207** [comment]
Giáo sư tâm huyết quá, mình xin phép report thêm một số lỗi này, gs cứ bình tĩnh sửa cũng được 
1. Một số tính năng của Bệ phóng tên lửa dịch chưa logic lắm, có thể dịch là đáp đất hoặc hạ cánh,...
![image](https://user-images.githubusercontent.com/90306428/132938833-957c6edb-3fc4-47ba-a779-c355e90f120b.png)

2. Ngôn ngữ ở thanh tiêu thụ thức ăn chưa dịch đồng bộ
![image](https://user-images.githubusercontent.com/90306428/132938852-5dc55c04-0ee1-48b9-b371-cf01762ad2b2.png)
![image](https://user-images.githubusercontent.com/90306428/132938864-2e4d9694-f242-4dc3-a215-374c9d665db1.png)

3. Mô tả Pin thông minh
![image](https://user-images.githubusercontent.com/90306428/132938985-05598e8f-aaac-4bf8-92db-508c07e0a288.png)

Thank you giáo sư, chúc giáo sư sức khỏe!

**Comment by sant1ago-hn** [comment]
> Giáo sư tâm huyết quá, mình xin phép report thêm một số lỗi này, gs cứ bình tĩnh sửa cũng được
> 
> 1. Một số tính năng của Bệ phóng tên lửa dịch chưa logic lắm, có thể dịch là đáp đất hoặc hạ cánh,...
>    ![image](https://user-images.githubusercontent.com/90306428/132938833-957c6edb-3fc4-47ba-a779-c355e90f120b.png)
> 2. Ngôn ngữ ở thanh tiêu thụ thức ăn chưa dịch đồng bộ
>    ![image](https://user-images.githubusercontent.com/90306428/132938852-5dc55c04-0ee1-48b9-b371-cf01762ad2b2.png)
>    ![image](https://user-images.githubusercontent.com/90306428/132938864-2e4d9694-f242-4dc3-a215-374c9d665db1.png)
> 3. Mô tả Pin thông minh
>    ![image](https://user-images.githubusercontent.com/90306428/132938985-05598e8f-aaac-4bf8-92db-508c07e0a288.png)
> 
> Thank you giáo sư, chúc giáo sư sức khỏe!

`DONE`

**Comment by dhm1207** [comment]
Hi giáo sư, mình lại update lỗi dịch này
![image](https://user-images.githubusercontent.com/90306428/136670255-d3ad7fb0-a179-4293-9803-5db3622a2591.png)
