### ISSUE TITLE
Thiếu dịch thuật DLC

### ISSUE THREAD

**Issue by Uzumaki-Boruto** [sant1ago-da-hanoi/oni-mods-descriptions#2]
![image](https://user-images.githubusercontent.com/17745812/136572308-58c8c1e4-b610-4aa4-9ccc-782da3a79621.png)

Gợi ý dịch: Kẻ cô độc
Khi thằng đệ này cô đơn ở thế giới này: +4 tất cả thuộc tính

**Comment by Uzumaki-Boruto** [comment]
![image](https://user-images.githubusercontent.com/17745812/136573116-0f717436-e514-4f81-81a7-029341acc887.png)

**Comment by Uzumaki-Boruto** [comment]
![image](https://user-images.githubusercontent.com/17745812/136576990-3599af47-15a1-4e16-a795-458130cea72a.png)

**Comment by sant1ago-hn** [comment]
`DONE`
