### ISSUE TITLE
Chưa dịch

### ISSUE THREAD

**Issue by dtagamingvn** [sant1ago-da-hanoi/oni-mods-descriptions#4]
Có chỗ này chưa dịch nếu có thời gian ad dịch luôn nhé 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/108244866/180106589-d37fcd3e-7d3e-4334-b744-48af0ffec2e1.png">

**Comment by sant1ago-hn** [comment]
Mình đã sửa và cập nhật bản mới vào ngày 04/07 rồi bạn nhé, bạn cập nhật lại mod và vào game xem còn lỗi không giúp mình nha <3
![image](https://user-images.githubusercontent.com/29042648/180128498-d9cf5499-5f2b-447e-b2b4-90189f3e8d9d.png)
